version: "3"

services:

  proxy:
    restart: always
    image: nginx:1.17.10
    container_name: proxy
    depends_on:
        - filebrowser
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./data/public:/public:z
    ports:
      - 80:80

  filebrowser:
    image: hurlenko/filebrowser
    user: "${_UID}:${_GID}"
    container_name: filebrowser
    volumes:
      - ./data:/data:z
      - ./filebrowserDB:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

  samba:
    restart: always
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TZ: "America/St_Johns"
      NMBD: "true"
      USER: "server;server" # Insecure password, only exposed to LAN
      USERID: "${_UID}"
      GROUPID: "${_GID}"
      SHARE: "share;/data;yes;no;no;server;'none';'none';'Home Server Files"
      RECYCLE: "disable" # Disable recycle bin
      SMB: "true" # Disables SMB2 minimum version
    ports:
      - "137:137/udp" 
      - "138:138/udp" 
      - "139:139/tcp" 
      - "445:445/tcp" 
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - ./data:/data:z
    command:  -p

  cloudflareDDNS:
      image: joshava/cloudflare-ddns
      restart: always
      container_name: cloudflareDDNS
      volumes:
        - ./ddns/config.yaml:/app/config.yaml

  handbrake:
    image: jlesage/handbrake
    restart: always
    environment:
      USER_ID: "${_UID}"
      GROUP_ID: "${_GID}"
      TZ: "America/St_Johns"
      AUTOMATED_CONVERSION_KEEP_SOURCE: 0
      AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS: "--preset-import-file /config/preset.json -Z MyPreset"
      AUTOMATED_CONVERSION_OVERWRITE_OUTPUT: 1
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - "./handbrake:/config:rw"
      - "./data:/storage:ro"
      - "./data/recordingQueue/:/watch:rw"
      - "./data/recordings:/output:rw"

  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./plausable/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./plausable/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    env_file:
      - .env
    ports:
      - 8000:80

  mcmyadmin:
    image: tekgator/docker-mcmyadmin:2.1.0
    container_name: mcmyadmin
    environment:
      PUID: "${_UID}"
      PGID: "${_GID}"
      EULA: 1
    volumes:
      - ./data/MC:/data
    ports:
      - 8888:8080
      - 25565:25565
      - 8123:8123
    stop_grace_period: 30s
    restart: unless-stopped


volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
